command from SSMS  ******/
SELECT 
[index]
     --,[SHIPPING_LOCATION]
      ,[DEPARTMENT]
      ,[CATEGORY]
      --,[SUBCATEGORY]
      ,[BREADCRUMBS]
     -- ,[SKU]
     -- ,[PRODUCT_URL]
      ,[PRODUCT NAME]
      ,[BRAND]
      ,[PRICE RETAIL]
      ,[PRICE CURRENT]
      ,[PRODUCT SIZE]
      --,[PROMOTION]
      ,[RunDate]
      --,[tid]
  FROM [Walmart].[dbo].['WalMart Sales Report$']